### ISSUE TITLE
cf_ prefix required for use of custom tags?

### ISSUE THREAD

**Issue by ChristianBeddows** [spraguey/cftextarea-lucee#1]
Hi,

Looking at use of this tag as a potential solution so we don't have to go through several apps and change the use of <cftextarea>, but lucee wont find the custom tag, and we believe it is because it expects custom tags to be prefixed with cf_ . Did you encounter this problem? Is there a way of getting around this?

**Comment by spraguey** [comment]
I did not encounter this, and it is not named that way in any of my
installs. After you placed the file in the library/tag folder, did you
recycle Lucee?


--
Michael J. Sprague
Director, Web Services
Hamilton College

315-859-4087
msprague@hamilton.edu

**Comment by ChristianBeddows** [comment]
Here's an example of how cftextarea is called in the old code:
`<cftextarea name="event_desc"  rows="3" cols="100"
            maxlength="4000" value="#v_event_desc#"
            validate="maxlength" wrap="virtual"></cftextarea>`

Lucee won't recognise the custom tag unless we change it to <cf_textarea> and as far as my research has show cf_ is required before all custom tags (without using something like cfimport).

After adding the file to the tag folder I added a mapping to the lucee server and completely reloaded the virtual machine.

**Comment by spraguey** [comment]
This is not a custom tag. I think that is why you are having trouble. To use this, you should not be adding mappings for a custom tag folder.

This is an actual tag that becomes part of the language. It needs to be installled to the library folder under the Lucee installation directory.
________________________________

**Comment by ChristianBeddows** [comment]
Ah, I had misunderstood. I have done it properly now and it all seems to be working.

Thanks for you help!
